# 
['Live', 'Death', 'Hell', 'Heaven', 'Programming'].each do |category_name|
  category = Category.create :name => category_name
  puts "Created category #{category.id}"
end

[
  {:title => 'Complex ruby examples',                  :body => 'Nunc elementum. Mauris purus. Maecenas ac lacinia quis, libero. Sed ligula enim eget lacus lacus magna, gravida feugiat venenatis, nunc commodo pulvinar mollis, purus est, dapibus vel, nibh. Cras interdum faucibus, diam id augue. Sed lobortis volutpat. Ut sagittis vel, eros. Etiam risus in magna nec nunc vel neque vitae metus feugiat quam molestie vitae, semper dui, ultrices posuere egestas volutpat.'},
  {:title => 'Where do the angels come from?',         :body => 'Litwo! Ojczyzno moja! Ty jesteś jak zdrowie. Nazywał się od oczu, Świecił się jak wiadomo, krzepcy, otyli i posępny obok pan Sędzia, z parkanu na przeciwnej szali. Zaś godna jest bez żadnych ozdób, ale nigdzie nie mógł schwytać. Wojskiego Woźny umiał komponować iżby je posłyszał, znikał nagle z łez, które na niem noty i opisuję, bo tak szanownych gości. W takim nigdy nie zawadzi. Bliskość piwnic wygodna służącej czeladzi. Tak każe przyzwoitość). nikt tam w zastępst'},
  {:title => 'How old is satan',                       :body => 'Drogi Marszałku, Wysoka Izbo. PKB rośnie Nikt inny was nie zapewni iż dokończenie aktualnych projektów koliduje z powodu kolejnych kroków w restrukturyzacji przedsiębiorstwa. Często niezauważanym szczegółem jest że, dalszy rozwój jest to, że wyeliminowanie korupcji wymaga sprecyzowania i znaczenia tych problemów nie trzeba udowadniać, ponieważ wdrożenie nowych, lepszych rozwiązań pomaga w większym stopniu tworzenie postaw uczestników wobec zadań programowych wymaga niezwykłej precyzji w przyszłościowe rozwiązania pomaga w restrukturyzacji przedsiębiorstwa.'},
  {:title => 'Where do the babies come from?',         :body => 'Początek traktatu czasu być niemateryalną, bo słówka jo, ja, je od niedolężności człowieczej przypisują. W nas zawisło, jeżeli jako Najwyższą Istność taka, która świętemu zrzodłu wszystkich rzeczach pewną jedność skojarzyć i szczęśliwości inaczej nabawiają człowieka sprawiedliwego Sędziego. Świętość ustawy czyli ograniczeniem i godności. To zaś są właśnie z najwyższą Inteligencyą, jako Istność jest jednoista lab jednotliwa, to jest Dobro, wolność jest co ująć od wszelkich moralnych zasad i poczciwo'},
  {:title => 'Where do we go after we die?',           :body => 'Алексей Федорович Карамазов был он, жив, ибо страстно желал благословиться у нас с места объясниться с своих странствий, о переписке. Познакомившись с умными и бог тебя не коснется. Ну что решительно сочли автора за что молодой человек особенный между могил. Домик, в ней Васенька, где-то на заграницу чего тому времени состарившийся'},
  {:title => 'How cheap is ketchup?',                  :body => 'Nunc elementum. Mauris purus. Maecenas ac lacinia quis, libero. Sed ligula enim eget lacus lacus magna, gravida feugiat venenatis, nunc commodo pulvinar mollis, purus est, dapibus vel, nibh. Cras interdum faucibus, diam id augue. Sed lobortis volutpat. Ut sagittis vel, eros. Etiam risus in magna nec nunc vel neque vitae metus feugiat quam molestie vitae, semper dui, ultrices posuere egestas volutpat.'},                                                                                                                                                                
  {:title => 'God is like Schrodingers cat',           :body => 'Litwo! Ojczyzno moja! Ty jesteś jak zdrowie. Nazywał się od oczu, Świecił się jak wiadomo, krzepcy, otyli i posępny obok pan Sędzia, z parkanu na przeciwnej szali. Zaś godna jest bez żadnych ozdób, ale nigdzie nie mógł schwytać. Wojskiego Woźny umiał komponować iżby je posłyszał, znikał nagle z łez, które na niem noty i opisuję, bo tak szanownych gości. W takim nigdy nie zawadzi. Bliskość piwnic wygodna służącej czeladzi. Tak każe przyzwoitość). nikt tam w zastępst'},
  {:title => 'God is like cheap oil - does not exist', :body => 'Drogi Marszałku, Wysoka Izbo. PKB rośnie Nikt inny was nie zapewni iż dokończenie aktualnych projektów koliduje z powodu kolejnych kroków w restrukturyzacji przedsiębiorstwa. Często niezauważanym szczegółem jest że, dalszy rozwój jest to, że wyeliminowanie korupcji wymaga sprecyzowania i znaczenia tych problemów nie trzeba udowadniać, ponieważ wdrożenie nowych, lepszych rozwiązań pomaga w większym stopniu tworzenie postaw uczestników wobec zadań programowych wymaga niezwykłej precyzji w przyszłościowe rozwiązania pomaga w restrukturyzacji przedsiębiorstwa.'},
  {:title => 'Why are people easily ofended',          :body => 'Początek traktatu czasu być niemateryalną, bo słówka jo, ja, je od niedolężności człowieczej przypisują. W nas zawisło, jeżeli jako Najwyższą Istność taka, która świętemu zrzodłu wszystkich rzeczach pewną jedność skojarzyć i szczęśliwości inaczej nabawiają człowieka sprawiedliwego Sędziego. Świętość ustawy czyli ograniczeniem i godności. To zaś są właśnie z najwyższą Inteligencyą, jako Istność jest jednoista lab jednotliwa, to jest Dobro, wolność jest co ująć od wszelkich moralnych zasad i poczciwo'}
].each do |attrs|
  categories = Category.all
  post = Post.create :title => attrs[:title], :body => attrs[:body]
  post.categories << categories.sample
  puts "Created post #{post.id}"
end